--SALES IS OUR CHILD TABLE ,THERE ARE TWO FOREIGN KEY AVAILABLE 
--CUSTOMER_ID & PRODUCT_ID

--IF WE WANT TO ADD FOREIGN KEY
ALTER TABLE SALES
ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);


--IF WE WANT TO ADD PRIMARY KEY
ALTER TABLE SALES
ADD PRIMARY KEY (CUSTOMER_ID);


--IF WE WANT TO DROP FOREIGN KEY
--ALTER TABLE 
--DROP FOREIGN KEY SALES FOREGIN KEY NAME;