--IF WE WANT TO DROP FOREIGN KEY
--ALTER TABLE 
--DROP FOREIGN KEY SALES FOREGIN KEY NAME;




--======================================================================================================
--THIS IS HOW WE ADD FOREIGN KEY
ALTER TABLE SALES
ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE;

ALTER TABLE SALES
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE;



--THIS IS HOW WE ADD PRIMARY KEY
ALTER TABLE SALES
ADD PRIMARY KEY (ORDER_ID);


--THIS IS HOW WE DROP PRIMARY KEY
ALTER TABLE SALES
DROP PRIMARY KEY;



--=======================================================
--Adding columns
ALTER TABLE CUSTOMER
ADD  EMAIL VARCHAR2(80);


ALTER TABLE CUSTOMER
ADD No_Of_Complaints NUMBER DEFAULT 0;


--ADDING UNIQUE KEY
ALTER TABLE CUSTOMER
ADD CONSTRAINT unique_email UNIQUE (EMAIL);


--DROPING UNIQUE KEY
ALTER TABLE CUSTOMER
DROP CONSTRAINT unique_email;

UPDATE CUSTOMER
SET EMAIL='sophia@gmail.com'
WHERE CUSTOMER_ID=6;




SELECT * FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE
WHERE SALARY=5000;

CREATE INDEX P1 
ON  EMPLOYEE(SALARY);

DESC EMPLOYEE;
ALTER TABLE EMPLOYEE
DROP INDEX ;

--To check how many indexes are there in table
SELECT *
FROM USER_INDEXES
WHERE TABLE_NAME='EMPLOYEE';

--To check on which column index is there
SELECT *
FROM USER_IND_COLUMNS
WHERE TABLE_NAME='EMPLOYEE';