--step 1 . create 1 department table ( Depart_ID PK , Depart_NAME unique )
CREATE TABLE DEPARTMENT(
DEPARTMENT_ID NUMBER(5) PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(50),
CONSTRAINT DEPT_NAME_UNIQUE UNIQUE (DEPARTMENT_NAME)
);

DESC  DEPARTMENT;
SELECT * 
FROM DEPARTMENT;


--Try to insert 5 records... 3 record with DENAME NULL
INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES(1,'IT');
INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES(2,'Sales');
INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES(3,Null);
INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES(4,Null);
INSERT INTO DEPARTMENT(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES(5,Null);


--Step2. Create EMP table( EID PK,ENAME NN,EMAIL UNIQUE,SAL CHECK,DID FK)

CREATE TABLE EMPLOYEE (
  Employee_id NUMBER PRIMARY KEY,
  Employee_NAME VARCHAR2(50) NOT NULL,
  EMAIL VARCHAR2(50) UNIQUE,
  SALARY NUMBER CHECK (SALARY >= 5000),
  Department_id NUMBER,
  CONSTRAINT fk_Department_id FOREIGN KEY (Department_id) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

SELECT *
FROM EMPLOYEE;

--INSERT 10 records into EMP table..
--try to check all constriants are working or not....
INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_NAME,EMAIL,SALARY,DEPARTMENT_ID)
VALUES(11,'Ritik','ritik@gmail.com',5000,1);

INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_NAME,EMAIL,SALARY,DEPARTMENT_ID)
VALUES(12,'Rohan','rohan@gm.com',8000,1);

INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_NAME,EMAIL,SALARY,DEPARTMENT_ID)
VALUES(13,'Rohit','rohit@gmail.com',6000,NULL);

INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_NAME,EMAIL,SALARY,DEPARTMENT_ID)
VALUES(13,'Rohit','rohit@gmail.com',Null,2);



--step3. Create new emp table again( EID pk, ENAME NN ,EMAIL UNIQUE NN ,SAL,DID)
---- imp...
CREATE TABLE EMPLOYEES(
 EMPLOYEE_ID NUMBER(5) ,
 EMPLOYEE_NAME VARCHAR2(50) NOT NULL,
 EMAIL VARCHAR2(70) UNIQUE NOT NULL, 
 SALARY NUMBER(8) CHECK(SALARY>=2000),
 DEPARTMENT_ID NUMBER(5)
);
--insert 5 records & test all constraint working
INSERT INTO EMPLOYEES(EMPLOYEE_ID,EMPLOYEE_NAME,EMAIL,SALARY,DEPARTMENT_ID)
VALUES(100,'Harshit','harshit@gmail.com',4500,10);

INSERT INTO EMPLOYEES(EMPLOYEE_ID,EMPLOYEE_NAME,EMAIL,SALARY,DEPARTMENT_ID)
VALUES(101,'Harshit','harshit@gmail.com',400,10);
--"Violated," it refers to a situation where a rule, constraint, or condition is not satisfied.

INSERT INTO EMPLOYEES(EMPLOYEE_ID,EMPLOYEE_NAME,EMAIL,SALARY,DEPARTMENT_ID)
VALUES(103,'Rakesh','rakesh@gmail.com',4500,10);


INSERT INTO EMPLOYEES(EMPLOYEE_ID,EMPLOYEE_NAME,EMAIL,SALARY,DEPARTMENT_ID)
VALUES(104,'abhishek','abishek@gmail.com',4500,10);





-- step 4.
--DEPT(DID) -- 10,20,30,40,50
--EMP(DID) --100,200 IMP IMP IMP .......................



