--THIS IS SALES TABLE 
CREATE TABLE  SALES(
 ORDER_ID NUMBER(5) NOT NULL,
 ORDER_DATE DATE,
 CUSTOMER_ID NUMBER,
 PRODUCT_ID VARCHAR2(10),
 PROFIT NUMBER(8) CHECK(PROFIT>100),
CONSTRAINT PKEY PRIMARY KEY(ORDER_ID) 
--FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE 
);


--===============================================================================================================
--THIS IS CUSTOMER TABLE
CREATE TABLE CUSTOMER(
 CUSTOMER_ID NUMBER(5) NOT NULL,
 CUSTOMER_NAME VARCHAR2(50),
 SEGMENT VARCHAR2(20),
 CITY VARCHAR2(20),
CONSTRAINT PKEY_OF_CUSTOMER PRIMARY KEY (CUSTOMER_ID) 
);



--THIS IS PRODUCT TABLE
CREATE TABLE PRODUCT(
  PRODUCT_ID VARCHAR2(10) NOT NULL,
  PRODUCT_NAME VARCHAR2(70),
  PRODUCT_QUANTITY NUMBER(5),
  PRODUCT_PRICE NUMBER(8),
CONSTRAINT PKEY_PRODUCT PRIMARY KEY (PRODUCT_ID)  
);
















--PRIMARY KEY CAN BE COMBINATION OF TWO OR THREE COLUMNS
--CREATE TABLE SALES(
-- ORDER_ID NUMBER(5) NOT NULL,
-- ORDER_DATE DATE,
-- CUSTOMER_ID NUMBER,
-- PRODUCT_ID VARCHAR2(10),
-- SALES NUMBER(10,2),
-- PROFIT NUMBER(8) CHECK(PROFIT>100),
--CONSTRAINT PKEY PRIMARY KEY (ORDER_ID,PRODUCT_ID) 
--);

